authorName: Vincent
experimentName: googlenet_dftuner
trialConcurrency: 1
maxExecDuration: 72h
maxTrialNum: 1000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  builtinTunerName: DFTuner
  classArgs:
    random_seed: 0
    num_init_evals: 2
    build_new_model_every: 5
trial:
  command: python train.py --seed 0 --log_path ./3-DFTuner.log
  codeDir: .
  gpuNum: 2
