authorName: Vincent
experimentName: dftuner_vgg16
trialConcurrency: 1
maxExecDuration: 60h
maxTrialNum: 1000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_hw.json
#choice: true, false
useAnnotation: false
tuner:
  builtinTunerName: CUHKPrototypeTuner
  classArgs:
    random_seed: 65
    num_init_evals: 2
    build_new_model_every: 5
trial:
  command: python train-nni.py --seed 65 --is_soo 0 --log_path ./3-DFTuner.log
  codeDir: .
  gpuNum: 2
