authorName: Vincent
experimentName: bohb_vgg16
trialConcurrency: 1
maxExecDuration: 60h
maxTrialNum: 1000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
##choice: true, false
useAnnotation: false
advisor:
  builtinAdvisorName: BOHB
  classArgs:
    optimize_mode: maximize
    min_budget: 3
    max_budget: 27
    eta: 3
    min_points_in_model: 9
    top_n_percent: 15
    num_samples: 64
    random_fraction: 0.0 #0.33
    bandwidth_factor: 3.0
    min_bandwidth: 0.001
trial:
  command: python train-nni.py --seed 64 --log_path ./1-BOHB.log
  codeDir: .
  gpuNum: 2
