authorName: Vincent
experimentName: boosted_trees
trialConcurrency: 1
maxExecDuration: 10h
maxTrialNum: 250
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
advisor:
  builtinAdvisorName: Hyperband
  classArgs:
    R: 20
    eta: 3
    optimize_mode: maximize
trial:
  command: python worker.py
  codeDir: .
  gpuNum: 1
