authorName: Vincent
experimentName: SOOInception
trialConcurrency: 1
maxExecDuration: 72h
maxTrialNum: 200
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
##choice: true, false
useAnnotation: false
advisor:
  builtinAdvisorName: BOHB
  classArgs:
    optimize_mode: maximize
    min_budget: 1
    max_budget: 5
    eta: 2
    min_points_in_model: 8
    top_n_percent: 15
    num_samples: 64
    random_fraction: 0.0 #0.33
    bandwidth_factor: 3.0
    min_bandwidth: 0.001
trial:
  command: python train-nni.py --seed 1234 --log_path ./1-BOHB.log
  codeDir: .
  gpuNum: 2